name: Build and Deploy to Azure

on:
  push:
    branches:
      - BuildGithubAction
  pull_request:
    branches:
      - BuildGithubAction

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies and Build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app-test
          path: |
            .
            !frontend/
