name: Code Coverage

on:
  push:
    branches:
      - testing
      - coverage
  pull_request:
    branches:
      - testing
      - coverage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pytest coverage
        run: |
          coverage run -m pytest
          coverage report