---
name: Python Unit Test

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
      - name: Test with pytest
        id: test
        working-directory: ./
        run: |
          python -m pytest
